### ISSUE TITLE
Build 1.3.15 for R=3.4.1?

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/r-rodbc-feedstock#5]
Currently, the available versions for r-rodbc are:
```
$ conda search r-rodbc
Loading channels: done
# Name                       Version           Build  Channel
r-rodbc                       1.3_14        r3.3.1_0  pkgs/r
r-rodbc                       1.3_14        r3.3.2_0  conda-forge
r-rodbc                       1.3_14        r3.3.2_0  pkgs/r
r-rodbc                       1.3_14        r3.4.1_0  conda-forge
r-rodbc                       1.3_14 r351h14c3975_1000  conda-forge
r-rodbc                       1.3_14  r351h470a237_0  conda-forge
r-rodbc                       1.3_15 mro343h086d26f_0  pkgs/r
r-rodbc                       1.3_15 mro350hbc2858b_0  pkgs/r
r-rodbc                       1.3_15 mro351hd10c6a6_0  pkgs/r
r-rodbc                       1.3_15        r3.4.1_0  pkgs/r
r-rodbc                       1.3_15  r342hb813f04_0  pkgs/r
r-rodbc                       1.3_15  r343h086d26f_0  pkgs/r
r-rodbc                       1.3_15  r350hb353451_0  pkgs/r
r-rodbc                       1.3_15  r351h96ca727_0  pkgs/r
r-rodbc                       1.3_15 r351h96ca727_1000  conda-forge
r-rodbc                       1.3_15  r351hc070d10_0  conda-forge
```

I'm building my whole stack from conda-forge (and need environments for both R=3.4 and R=3.5), and would need `r-rodbc>=1.3.15` also on R=3.4. I'd like to avoid having to change to defaults for this (cf. conda/conda#8533), so I was wondering if it would be possible to make a build for that combination as well?

**Comment by dpryan79** [comment]
Why does your stack still need R 3.4? That was replaced a year ago and nothing (in conda-forge) has been built for it since summer 2018.

**Comment by h-vetinari** [comment]
@dpryan79 
There's a bunch of applications that are being migrated, but the environments I'm building should have both versions available. :)

**Comment by dpryan79** [comment]
I suspect this will be a "pull request welcome, but none of us are likely to do this ourselves" sort of things. You could make a pull request that adds a `conda_build_config.yaml` with `r-base=3.4.1` in it, but note that you'll also have to either revert to older compilers (easier) or get R rebuilt with newer pinnings. I hope this is one of the few packages you need, since it would be a fair bit of work to do this for a lot of repositories.

**Comment by bgruening** [comment]
Hi @h-vetinari.

We only build against the latest R version, as Devon pointed out, for multiple reasons and defaults are also not building for 3.4 anymore as far as I know.
Moreover, I don't think you can mix R3.4 and R3.5 in one environment without a bunch of problems.

**Comment by h-vetinari** [comment]
> Moreover, I don't think you can mix R3.4 and R3.5 in one environment without a bunch of problems.

Sorry, that was badly worded on my part. I'm providing one for R=3.4 and one for R=3.5.

**Comment by jdblischak** [comment]
@h-vetinari Have you tried locally building r-rodbc with r-base 3.4.1? I ran

```
conda build --R 3.4.1 r-rodbc/
```

and then uploaded the result to my personal channel on Anaconda Cloud. You can see if the result is compatible with your R 3.4.1 environment with:

```
conda install -c jdblischak r-rodbc
```

**Comment by h-vetinari** [comment]
@jdblischak 
Thanks a lot, the package in your personal channel works well (in an outside testing environment). Unfortunately, I cannot access this channel where I need to install things (proxy allows just defaults and conda-forge), and I haven't managed to execute `conda build`.

Would it be possible to publish the package you built to this feedstock, so that it appears in conda-forge?

**Comment by jdblischak** [comment]
> Thanks a lot, the package in your personal channel works well (in an outside testing environment). 

That's promising at least.

> Unfortunately, I cannot access this channel where I need to install things (proxy allows just defaults and conda-forge),

Do you think it would be possible to allow your proxy to access your personal channel or a channel that is dedicated to your organization?

> and I haven't managed to execute conda build.

What have you tried? Are you familiar with writing conda recipes and building conda packages? I created the recipe with our [conda_r_skeleton_helper](https://github.com/bgruening/conda_r_skeleton_helper) script and then manually added `unixodbc` as a requirement. You can see my recipe [here](https://github.com/jdblischak/jdb-conda/blob/509b7189790da82053a1ef4dbd7066746783ccee/recipes/r-rodbc/meta.yaml).

> Would it be possible to publish the package you built to this feedstock, so that it appears in conda-forge?

As the other maintainers noted, this is likely to be a pain given how much the conda-forge infrastructure has changed since we regularly built R packages for R 3.4.1. I am trying to use `conda_build_config.yaml` to build for 3.4.1, but unsurprisingly it's not going well.

What operating systems do you need to support?

**Comment by jdblischak** [comment]
Update. I was able to build for R 3.4.1 on Travis (macOS) and AppVeyor (Windows):

https://travis-ci.com/jdblischak/r-rodbc-feedstock/builds/107848147#L706
https://ci.appveyor.com/project/jdblischak/r-rodbc-feedstock/builds/23750640#L804

Unfortunately the CircleCI builds of my fork keep failing to even spin up the environment, so I don't know if that will work.

https://circleci.com/gh/jdblischak/r-rodbc-feedstock

**Comment by h-vetinari** [comment]
@jdblischak 
Wow, thanks for taking a shot at this! :)

> What operating systems do you need to support?

> Update. I was able to build for R 3.4.1 on Travis (macOS) and AppVeyor (Windows):

Unfortunately for me, it would be linux (ubuntu 18.04).

**Comment by h-vetinari** [comment]
> Unfortunately the CircleCI builds of my fork keep failing to even spin up the environment, so I don't know if that will work.

Are there logs of that somewhere? All I see is that the jobs are either still running (or at least trying to), or something like:

```
We had an unexpected error preparing a VM for this build, potentially due to our infrastructure or cloud provider.  Please retry the build in a few minutes

Unexpected environment preparation error: failed to create a vm: instance not ready yet: unassigned
```

**Comment by jdblischak** [comment]
> Wow, thanks for taking a shot at this! :)

@h-vetinari No problem! I like a good challenge :-)

> Are there logs of that somewhere? All I see is that the jobs are either still running (or at least trying to), or something like:

That was exactly my point. The failure is uninformative as to whether the conda recipe can be built. It's just CircleCI failing to start for some reason.

Let's see how PR #6 does. Fingers crossed!

**Comment by jdblischak** [comment]
@h-vetinari r-rodbc has been built for R 3.4.1 for Linux, macOS, and Windows:

https://anaconda.org/conda-forge/r-rodbc/files?version=1.3_15

**Comment by h-vetinari** [comment]
@jdblischak 
Thank you very much! :)

I now see the package in `conda search r-rodbc`, but trying to install it (in isolation at least) still runs into conda/conda#8533, unfortunately... :(

**Comment by h-vetinari** [comment]
Nevermind, I solved that, and it installs fine! :)

**Comment by jdblischak** [comment]
> Nevermind, I solved that, and it installs fine! :)

@h-vetinari OK. Good. I was confused because I wasn't able to replicate the error. The command below works on my local Ubuntu 18.04 and in the Docker image [continuumio/miniconda3](https://hub.docker.com/r/continuumio/miniconda3) (both with conda 4.6.11):

```
# conda config --add channels conda-forge
conda create -y -n test-rodbc r-rodbc r-base=3.4.1
```
